services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - andys_db_url=jdbc:postgresql://db:5433/andys
      - andys_db_user=andy
      - andys_db_password=andy
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=andys
      - POSTGRES_USER=andy
      - POSTGRES_PASSWORD=andy
    expose:
      - 5433
    ports:
      - 5433:5433
    healthcheck:
      test: [ "CMD", "pg_isready" , "-U", "andy", "-p", "5433", "-d", "andys" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: -p 5433
volumes:
  db-data:

