jwt.secret: EWbFtjV/y2algCtEhYwuaZdWSg2BhN2SGv4EP465Pk0=
spring:
  datasource:
    url: ${andys_db_url:jdbc:postgresql://localhost:5432/andys}
    username: ${andys_db_user:root}
    password: ${andys_db_password:root}
  activemq:
    broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
    in-memory: true
    non-blocking-redelivery: true
    packages:
    trust-all: false
    trusted: com.github.aistomin
    pool:
      block-if-full: true
      block-if-full-timeout: -1
      enabled: false
      idle-timeout: 30000
      max-connections: 1
      max-sessions-per-connection: 500
      time-between-expiration-check: -1
      use-anonymous-producers: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
#    open-in-view: false
    hibernate:
      ddl-auto: ${andys_ddl_auto:create-drop}
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQLDialect
support.email: support@mailinator.com