spring:
  datasource:
    url: ${andys_db_url:jdbc:postgresql://localhost:5432/andys}
    username: ${andys_db_user:root}
    password: ${andys_db_password:root}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: ${andys_ddl_auto:create-drop}
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQL81Dialect