name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Start PostgreSQL on Ubuntu
      run: |
        sudo systemctl start postgresql.service
        pg_isready
    - name: Create additional user
      run: |
        sudo -u postgres psql --command="CREATE USER joe PASSWORD 'foo'" --command="\du"
    - name: Create additional database
      run: |
        sudo -u postgres createdb --owner=joe andys
        PGPASSWORD=foo psql --username=joe --host=localhost --list timetable
    - name: Build with Maven
      run: mvn clean install package javadoc:javadoc
      env:
        andys_db_url: jdbc:postgresql://localhost:5432/andys
        andys_db_user: joe
        andys_db_password: foo
    - name: Publish Codecov
      run: bash <(curl -s https://codecov.io/bash)
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
